paths:
  local:  # robot desktop
    rd_rl: /home/openarm14/ws/junmo_cho/rd-rl
    checkpoints: /home/openarm14/ws/junmo_cho/checkpoint
    dataset: /home/openarm14/ws/junmo_cho/rd-rl/rl-dataset

  learner:  # training server
    rd_rl: /data/junmo_cho/workspace/rd-rl
    checkpoints: /data/rlwrld-unified-checkpoints/junmo_cho/checkpoints
    dataset: /data/junmo_cho/workspace/rd-rl/rl-dataset

learner:
  namespace: p-rlwrld
  pod: junmo-cho-data-pod
